name:                bel-expr
version:             0.1.0.0
github:              "githubuser/bel-expr"
license:             MIT
author:              "Reza Handzalah"
maintainer:          "example@example.com"
copyright:           "2025 Reza Handzalah"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bel-expr#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- megaparsec
- hashable
- unordered-containers
- text
- bytestring
- aeson
- random
- time
- regex-posix
- scientific
- aeson-jsonpath >= 0.3.0.2 && < 0.4.0.0
- vector
- QuickCheck
- tasty-quickcheck

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - BEL.BatteriesMain
  - BEL

executables:
  bel-expr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bel-expr

tests:
  bel-expr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bel-expr
    - tasty
    - tasty-hunit
